SELECT DB_NAME();

CREATE TABLE Hoa (
    MaHoa INT IDENTITY(1,1) PRIMARY KEY,
    TenHoa NVARCHAR(100) NOT NULL,
    Gia MONEY NOT NULL,
    SoLuong INT NOT NULL,
    MoTa NVARCHAR(255) NULL
);
SELECT * FROM Hoa;

CREATE TABLE NhanVien (
    MaNV INT IDENTITY(1,1) PRIMARY KEY,
    TenNV NVARCHAR(100) NOT NULL,
    ChucVu NVARCHAR(50),
    SoDienThoai VARCHAR(15) UNIQUE
);
SELECT * FROM NhanVien;

CREATE TABLE KhachHang (
    MaKH INT IDENTITY(1,1) PRIMARY KEY,
    TenKH NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(200),
    SoDienThoai VARCHAR(15) UNIQUE
);
SELECT * FROM KhachHang;

CREATE TABLE KhuyenMai (
    MaKM INT IDENTITY(1,1) PRIMARY KEY,
    TenCT NVARCHAR(100) NOT NULL,
    TyLeGiam DECIMAL(5,2) NOT NULL,
    NgayBD DATE NOT NULL,
    NgayKT DATE NOT NULL
);
SELECT * FROM KhuyenMai

CREATE TABLE DonHang (
    MaDH INT IDENTITY(1,1) PRIMARY KEY,
    MaKH INT NOT NULL,
    MaNV INT NOT NULL,
    NgayDatHang DATE NOT NULL DEFAULT GETDATE(),
    TongTien MONEY NOT NULL,
    MaKM INT NULL,
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    FOREIGN KEY (MaKM) REFERENCES KhuyenMai(MaKM)
);
SELECT * FROM DonHang;

CREATE TABLE ChiTietDonHang (
    MaDH INT NOT NULL,
    MaHoa INT NOT NULL,
    SoLuong INT NOT NULL,
    ThanhTien MONEY NOT NULL,
    PRIMARY KEY (MaDH, MaHoa),
    FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH),
    FOREIGN KEY (MaHoa) REFERENCES Hoa(MaHoa)
);
SELECT * FROM ChiTietDonHang;
